name: Build wheels and sdist and upload to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  # This doesn't actually need to be split up into two jobs, but if we eventually
  # add some C-layer code, then we'll want to have the first job use cibuildwheel
  # on multiple os's.  So leave it this way.
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U numpy setuptools
          pip install -U -r requirements.txt

      - name: Build wheels
        run: |
          pip install wheel
          mkdir wheelhouse
          pip wheel -w wheelhouse .

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/Piff*.whl

  build_sdist:
    name: Build sdist and upload to PyPI
    needs: build_wheels
    # Just need to build sdist on a single machine
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U numpy setuptools
          pip install -U -r requirements.txt

      - name: Download wheels
        uses: actions/download-artifact@v2
        with:
          path: ./wheels

      - name: Build sdist
        run: |
          python setup.py sdist
          ls -l dist
          tar tvfz dist/Piff-*.tar.gz

      - name: Copy wheels
        run: |
          echo ls -l wheels
          ls -l wheels
          echo ls -l wheels/artifact
          ls -l wheels/artifact
          cp wheels/artifact/*.whl dist
          echo ls -l dist
          ls -l dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            user: rmjarvis
            password: ${{ secrets.PYPI_PASSWORD }}
            verbose: true
